### ISSUE TITLE
New feature for part 1

### ISSUE THREAD

**Issue by dwakeman** [SweetJenn23/BlockchainLab#4]
I hit the part of the lab where I got the permission error.   I couldn't remember what value I used in the asset, so I had to cancel out and go back to the asset to find the current value.  When I went back to submit the transaction again, I forgot to update the teamId; when I submitted the transaction I got the error that means the asset doesn't exist.  

I knew what that meant and was easily able to recover in a few seconds, but students doing the lab for the first time may not know what happened.  I like how you added tips for this sort of thing, and think this would be a good one to add to the document.

**Comment by SweetJenn23** [comment]
@dwakeman I added this. How does it look? 
![image](https://user-images.githubusercontent.com/14825742/27688771-be9fd148-5cd3-11e7-88ea-a88288f2ae1d.png)

**Comment by dwakeman** [comment]
@SweetJenn23 Perfect.  Of all the places for a student to make a mistake, that will be the big one.  I know I hit it time and time again when I was building my first business network.  I think this covers it well.
